name: Deploy Production to Cloud

on:
    release:
        types: [published]

jobs:
    build-and-push:
        name: Build and Push Docker Image for Production (Cloud)
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.2.2

            - name: Capture release version
              run: echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2.0.1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.10.0

            - name: Extract Docker Metadata
              id: meta
              uses: docker/metadata-action@v5.7.0
              with:
                  images: |
                      ${{ steps.login-ecr.outputs.registry }}/kodus-orchestrator-prod
                  tags: |
                      type=semver,pattern={{version}}
                      type=raw,value=latest

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v6.15.0
              with:
                  context: .
                  file: ./DockerFiles/Dockerfile.prod
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      API_CLOUD_MODE=true
                      RELEASE_VERSION=${{ env.RELEASE_VERSION }}

            - name: Log out of Amazon ECR
              if: always()
              run: docker logout ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            - name: Notificar Discord sobre Sucesso
              if: success()
              uses: sarisia/actions-status-discord@v1.15.3
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  content: ":tada: A imagem Docker versão `${{ env.RELEASE_VERSION }}` foi construída e enviada com sucesso para o Amazon ECR."
                  title: "Build e Push: kodus-orchestrator"
                  username: "GitHub Actions"
                  color: 0x00FF00

            - name: Notificar Discord sobre Falha
              if: failure()
              uses: sarisia/actions-status-discord@v1.15.3
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  content: ":x: Falha ao construir ou enviar a imagem Docker versão `${{ env.RELEASE_VERSION }}` para o Amazon ECR. Verifique os logs para mais detalhes."
                  title: "Build e Push: kodus-orchestrator"
                  username: "GitHub Actions"
                  color: 0xFF0000
